export const actions = {
  profile: {
    DATA_FATCHING: "PROFILE_DATA_FATCHING",
    DATA_SUCCESS: "PROFILE_DATA_SUCCESS",
    DATA_FAIL: "PROFILE_DATA_FAIL",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMG_UPLOADED: "PROFILE_IMG_UPLOADED",
  },

  post: {
    DATA_FATCHING: "POST_DATA_FATCHING",
    DATA_SUCCESS: "POST_DATA_SUCCESS",
    DATA_FAIL: "POST_DATA_FAIL",
    DATA_EDITED: "POST_DATA_EDITED",
    POST_DELETED: "POST_DELETED",
    NEW_POST_ADDED: "NEW_POST_ADDED",
  },
};
