export const actions = {
  profile: {
    DATA_FATCHING: "PROFILE_DATA_FATCHING",
    DATA_SUCCESS: "PROFILE_DATA_SUCCESS",
    DATA_FAIL: "PROFILE_DATA_FAIL",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMG_UPLOADED: "PROFILE_IMG_UPLOADED",
  },
};
